spring.application.name=tictactoe-game-service
logging.level.com.svi.spring.tictactoe-game-service=DEBUG

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=batch1_2026_trainees
spring.cassandra.local-datacenter=datacenter1